#!/bin/bash
set -e
ebnf/Ebnf OMG_OntoIOp_current.tex 
pdflatex ebnf-OMG_OntoIOp_current.tex
temp=$(mktemp -d)
pdftk ebnf-OMG_OntoIOp_current.pdf cat 1-73 output $temp/dol1.pdf
pdftk ebnf-OMG_OntoIOp_current.pdf cat 75-77 output $temp/dol2.pdf
pdftk ebnf-OMG_OntoIOp_current.pdf cat 79-end output $temp/dol3.pdf
rm dol.pdf
pdftk $temp/dol1.pdf mof/oms.pdf $temp/dol2.pdf mof/oms-mappings.pdf $temp/dol3.pdf cat output dol.pdf
rm -r $temp
