#!/bin/bash
diff -u OMG_OntoIOp_current-diff-all.tex OMG_OntoIOp_current-diff-$1_*.tex --label OMG_OntoIOp_current-diff-all.tex  --label OMG_OntoIOp_current-diff-all.tex > diff-$1
sed -i diff-$1 -re '3,12d' 
